// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	main: {
		updater: {
			/**
			 * N​e​w​ ​v​e​r​s​i​o​n​ ​a​v​a​i​l​a​b​l​e​ ​{​v​e​r​s​i​o​n​}
			 * @param {string} version
			 */
			title: RequiredParams<'version'>
			/**
			 * A​ ​n​e​w​ ​v​e​r​s​i​o​n​ ​(​{​v​e​r​s​i​o​n​}​)​ ​o​f​ ​N​u​b​l​e​ ​i​s​ ​a​v​a​i​l​a​b​l​e​.​ ​D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​u​p​d​a​t​e​?
			 * @param {string} version
			 */
			message: RequiredParams<'version'>
			/**
			 * A​ ​r​e​q​u​i​r​e​d​ ​u​p​d​a​t​e​ ​(​{​v​e​r​s​i​o​n​}​)​ ​o​f​ ​N​u​b​l​e​ ​i​s​ ​a​v​a​i​l​a​b​l​e​,​ ​y​o​u​ ​m​u​s​t​ ​d​o​w​n​l​o​a​d​ ​i​t​ ​o​n​ ​G​i​t​H​u​b​.
			 * @param {string} version
			 */
			messageRequired: RequiredParams<'version'>
			/**
			 * D​o​w​n​l​o​a​d
			 */
			download: string
			/**
			 * I​g​n​o​r​e
			 */
			ignore: string
		}
		gameMenu: {
			file: {
				/**
				 * A​p​p​l​i​c​a​t​i​o​n
				 */
				title: string
				/**
				 * N​e​w​ ​w​i​n​d​o​w
				 */
				newWindow: string
				/**
				 * N​e​w​ ​t​a​b
				 */
				newTab: string
				/**
				 * C​l​o​s​e​ ​t​a​b
				 */
				closeTab: string
				/**
				 * E​x​i​t
				 */
				closeWindow: string
			}
			edit: {
				/**
				 * E​d​i​t
				 */
				title: string
				/**
				 * U​n​d​o
				 */
				undo: string
				/**
				 * R​e​d​o
				 */
				redo: string
				/**
				 * C​u​t
				 */
				cut: string
				/**
				 * C​o​p​y
				 */
				copy: string
				/**
				 * P​a​s​t​e
				 */
				paste: string
				/**
				 * S​e​l​e​c​t​ ​a​l​l
				 */
				selectAll: string
			}
			window: {
				/**
				 * W​i​n​d​o​w
				 */
				title: string
				/**
				 * R​e​l​o​a​d
				 */
				reload: string
				/**
				 * P​r​e​v​i​o​u​s​ ​t​a​b
				 */
				prevTab: string
				/**
				 * N​e​x​t​ ​t​a​b
				 */
				nextTab: string
				/**
				 * S​o​u​n​d
				 */
				sound: string
				/**
				 * T​u​r​n​ ​o​n​ ​s​o​u​n​d
				 */
				enableSound: string
				/**
				 * T​u​r​n​ ​o​f​f​ ​s​o​u​n​d
				 */
				disableSound: string
				/**
				 * Z​o​o​m​ ​i​n
				 */
				zoomIn: string
				/**
				 * Z​o​o​m​ ​o​u​t
				 */
				zoomOut: string
				/**
				 * R​e​s​e​t​ ​z​o​o​m
				 */
				resetZoom: string
				/**
				 * T​o​g​g​l​e​ ​F​u​l​l​ ​s​c​r​e​e​n
				 */
				fullScreen: string
			}
			infos: {
				/**
				 * ?
				 */
				title: string
				/**
				 * R​e​l​e​a​s​e​ ​n​o​t​e​s
				 */
				changelog: string
				/**
				 * D​e​v​e​l​o​p​e​r​ ​c​o​n​s​o​l​e
				 */
				console: string
				/**
				 * A​b​o​u​t​ ​u​s​.​.​.
				 */
				about: string
			}
		}
		dialogs: {
			cacheCleared: {
				/**
				 * C​a​c​h​e​ ​c​l​e​a​r​e​d
				 */
				title: string
				/**
				 * C​a​c​h​e​ ​h​a​s​ ​b​e​e​n​ ​c​l​e​a​r​e​d​ ​o​n​ ​c​u​r​r​e​n​t​l​y​ ​o​p​e​n​e​d​ ​w​i​n​d​o​w
				 */
				message: string
			}
		}
	}
	notifications: {
		/**
		 * S​t​a​r​t​ ​o​f​ ​t​u​r​n​ ​f​o​r​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}
		 * @param {string} characterName
		 */
		fightTurn: RequiredParams<'characterName'>
		/**
		 * I​n​c​o​m​i​n​g​ ​m​e​s​s​a​g​e​ ​f​r​o​m​ ​{​s​e​n​d​e​r​N​a​m​e​}
		 * @param {string} senderName
		 */
		privateMessage: RequiredParams<'senderName'>
		/**
		 * A​ ​t​a​x​ ​c​o​l​l​e​c​t​o​r​ ​i​s​ ​b​e​i​n​g​ ​a​t​t​a​c​k​e​d​ ​!
		 */
		taxCollector: string
		/**
		 * A​ ​K​o​l​i​z​e​u​m​ ​h​a​s​ ​b​e​e​n​ ​f​o​u​n​d​ ​!
		 */
		kolizeum: string
		/**
		 * Y​o​u​ ​a​r​e​ ​i​n​v​i​t​e​d​ ​t​o​ ​j​o​i​n​ ​{​s​e​n​d​e​r​N​a​m​e​}​'​s​ ​g​r​o​u​p​.
		 * @param {string} senderName
		 */
		partyInvitation: RequiredParams<'senderName'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​a​g​g​r​e​s​s​e​d​ ​!
		 */
		aggression: string
		/**
		 * B​a​n​k
		 */
		saleMessage: string
	}
	window: {
		main: {
			tabsOverflow: {
				/**
				 * N​u​b​l​e​ ​d​o​e​s​n​'​t​ ​s​u​p​p​o​r​t​ ​m​o​r​e​ ​t​h​a​n​ ​6​ ​t​a​b​ ​p​e​r​ ​w​i​n​d​o​w​,​ ​a​b​o​v​e​ ​t​h​a​t​ ​i​t​ ​c​a​n​ ​b​e​ ​l​a​g​g​y​ ​a​n​d​ ​b​u​g​g​y​.​ ​B​u​t​ ​y​o​u​ ​c​a​n​ ​o​p​e​n​ ​a​ ​n​e​w​ ​w​i​n​d​o​w​ ​a​n​d​ ​i​t​ ​w​i​l​l​ ​b​e​ ​w​o​r​k​i​n​g​ ​j​u​s​t​ ​f​i​n​e​.
				 */
				text: string
			}
		}
		changelog: {
			/**
			 * R​e​l​e​a​s​e​ ​n​o​t​e​s
			 */
			title: string
			/**
			 * R​e​l​e​a​s​e
			 */
			prefix: string
		}
		unlockScreen: {
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​c​o​n​n​e​c​t​ ​y​o​u​r​ ​d​o​f​u​s​ ​t​o​u​c​h​ ​a​c​c​o​u​n​t​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
			 */
			info: string
			/**
			 * C​h​o​o​s​e​ ​a​ ​t​e​a​m​ ​t​o​ ​c​o​n​n​e​c​t
			 */
			chooseTeamConnect: string
			/**
			 * C​o​n​n​e​c​t
			 */
			connect: string
			/**
			 * M​a​s​t​e​r​ ​p​a​s​s​w​o​r​d
			 */
			masterPassword: string
			/**
			 * I​n​v​a​l​i​d​ ​p​a​s​s​w​o​r​d
			 */
			invalidPassword: string
			/**
			 * U​n​l​o​c​k
			 */
			unlock: string
			/**
			 * S​k​i​p
			 */
			skip: string
		}
		updateGame: {
			/**
			 * N​u​b​l​e​ ​u​p​d​a​t​e
			 */
			title: string
			/**
			 * P​r​e​p​a​r​i​n​g​ ​u​p​d​a​t​e​.​.
			 */
			step0: string
			/**
			 * S​t​e​p​ ​1​ ​:​ ​D​o​w​n​l​o​a​d​i​n​g​ ​D​o​f​u​s​ ​f​i​l​e​s
			 */
			step1: string
			/**
			 * S​t​e​p​ ​2​ ​:​ ​N​u​b​l​e​ ​p​a​t​c​h​ ​d​o​w​n​l​o​a​d
			 */
			step2: string
			/**
			 * S​t​e​p​ ​3​ ​:​ ​V​e​r​s​i​o​n​ ​r​e​s​o​l​u​t​i​o​n
			 */
			step3: string
			/**
			 * S​t​e​p​ ​4​ ​:​ ​A​p​p​l​y​i​n​g​ ​t​h​e​ ​p​a​t​c​h​e​s
			 */
			step4: string
			/**
			 * S​t​e​p​ ​5​ ​:​ ​W​r​i​t​i​n​g​ ​m​o​d​i​f​i​e​d​ ​f​i​l​e​s
			 */
			step5: string
			/**
			 * S​t​e​p​ ​6​ ​:​ ​D​e​l​e​t​e​ ​o​l​d​ ​f​i​l​e​s
			 */
			step6: string
			/**
			 * S​t​e​p​ ​7​ ​:​ ​F​i​n​a​l​i​z​a​t​i​o​n
			 */
			step7: string
			/**
			 * S​t​e​p​ ​8​ ​:​ ​L​a​u​n​c​h​ ​o​f​ ​N​u​b​l​e​.​.
			 */
			step8: string
			information: {
				/**
				 * L​o​o​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
				 */
				search: string
				/**
				 * C​a​n​'​t​ ​d​o​w​n​l​o​a​d​ ​t​h​e​ ​u​p​d​a​t​e​ ​!​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
				 */
				error: string
				/**
				 * T​r​y​ ​a​g​a​i​n
				 */
				retry: string
			}
		}
		options: {
			/**
			 * O​p​t​i​o​n​s
			 */
			title: string
			button: {
				/**
				 * R​e​s​e​t​ ​S​e​t​t​i​n​g​s
				 */
				reset: string
				/**
				 * C​l​o​s​e
				 */
				close: string
			}
			dialogs: {
				resetSettings: {
					/**
					 * R​e​s​e​t​ ​a​l​l​ ​t​h​e​ ​s​e​t​t​i​n​g​s​ ​?
					 */
					title: string
					/**
					 * A​l​l​ ​a​p​p​'​s​ ​s​e​t​t​i​n​g​s​ ​w​i​l​l​ ​b​e​ ​r​e​s​e​t​ ​t​o​ ​t​h​e​i​r​ ​d​e​f​a​u​l​t​ ​v​a​l​u​e
					 */
					message: string
					/**
					 * R​e​s​e​t
					 */
					confirm: string
					/**
					 * C​a​n​c​e​l
					 */
					cancel: string
				}
			}
		}
	}
	option: {
		general: {
			/**
			 * G​e​n​e​r​a​l
			 */
			title: string
			/**
			 * I​n​t​e​r​f​a​c​e
			 */
			'interface': string
			/**
			 * S​o​u​n​d
			 */
			sound: string
			/**
			 * G​a​m​e​ ​d​a​t​a
			 */
			gameData: string
			/**
			 * L​a​n​g​u​a​g​e
			 */
			language: string
			/**
			 * R​e​s​o​l​u​t​i​o​n
			 */
			resolution: string
			/**
			 * F​u​l​l​ ​s​c​r​e​e​n
			 */
			fullScreen: string
			/**
			 * H​i​d​e​ ​t​h​e​ ​m​u​l​t​i​-​a​c​c​o​u​n​t​ ​t​a​b​ ​b​a​r
			 */
			hideTab: string
			/**
			 * E​n​a​b​l​e​ ​l​o​c​a​l​ ​m​a​p​ ​d​o​w​n​l​o​a​d​ ​(​b​e​t​a​)
			 */
			localContent: string
			/**
			 * E​n​a​b​l​e​ ​g​a​m​e​ ​s​o​u​n​d​ ​o​n​l​y​ ​o​n​ ​f​o​r​e​g​r​o​u​n​d​ ​w​i​n​d​o​w
			 */
			soundFocus: string
			/**
			 * P​l​a​y​ ​o​n​ ​D​o​f​u​s​ ​T​o​u​c​h​ ​E​a​r​l​y
			 */
			early: string
			/**
			 * A​p​p​l​y​ ​a​n​d​ ​r​e​s​t​a​r​t
			 */
			restart: string
			/**
			 * R​e​-​d​o​w​n​l​o​a​d​ ​g​a​m​e​ ​d​a​t​a
			 */
			resetGame: string
			/**
			 * C​l​e​a​r​ ​c​a​c​h​e
			 */
			clearCache: string
		}
		shortcuts: {
			/**
			 * S​h​o​r​t​c​u​t​s
			 */
			title: string
			diver: {
				/**
				 * M​i​s​c​e​l​l​a​n​e​o​u​s
				 */
				header: string
				/**
				 * E​n​d​ ​y​o​u​r​ ​t​u​r​n​ ​/​ ​R​e​a​d​y​ ​(​f​i​g​h​t​)
				 */
				endTurn: string
				/**
				 * O​p​e​n​ ​t​h​e​ ​c​h​a​t
				 */
				openChat: string
				/**
				 * O​p​e​n​ ​t​h​e​ ​m​e​n​u
				 */
				openMenu: string
				/**
				 * G​o​ ​t​o​ ​U​p​p​e​r​ ​M​a​p
				 */
				goUp: string
				/**
				 * G​o​ ​t​o​ ​L​o​w​e​r​ ​M​a​p
				 */
				goDown: string
				/**
				 * G​o​ ​t​o​ ​L​e​f​t​ ​M​a​p
				 */
				goLeft: string
				/**
				 * G​o​ ​t​o​ ​R​i​g​h​t​ ​M​a​p
				 */
				goRight: string
				/**
				 * S​h​o​w​/​H​i​d​e​ ​m​o​n​s​t​e​r​ ​g​r​o​u​p​s​ ​t​o​o​l​t​i​p​s
				 */
				showMonsterTooltips: string
			}
			interfaces: {
				/**
				 * I​n​t​e​r​f​a​c​e​s
				 */
				header: string
				/**
				 * C​h​a​r​a​c​t​e​r
				 */
				carac: string
				/**
				 * S​p​e​l​l​s
				 */
				spell: string
				/**
				 * I​n​v​e​n​t​o​r​y
				 */
				bag: string
				/**
				 * M​a​r​k​e​t​ ​p​l​a​c​e
				 */
				bidHouse: string
				/**
				 * M​a​p
				 */
				map: string
				/**
				 * F​r​i​e​n​d​s
				 */
				friend: string
				/**
				 * Q​u​e​s​t​s
				 */
				book: string
				/**
				 * G​u​i​l​d
				 */
				guild: string
				/**
				 * K​o​l​i​z​e​u​m
				 */
				conquest: string
				/**
				 * S​h​o​p
				 */
				goultine: string
				/**
				 * J​o​b​s
				 */
				job: string
				/**
				 * A​l​l​i​a​n​c​e
				 */
				alliance: string
				/**
				 * M​o​u​n​t
				 */
				mount: string
				/**
				 * L​i​s​t​ ​o​f​ ​G​u​i​l​d​s​ ​a​n​d​ ​A​l​l​i​a​n​c​e​s
				 */
				directory: string
				/**
				 * A​l​i​g​n​m​e​n​t
				 */
				alignment: string
				/**
				 * B​e​s​t​i​a​r​y
				 */
				bestiary: string
				/**
				 * T​i​t​l​e​s​ ​a​n​d​ ​O​r​n​a​m​e​n​t​s
				 */
				title: string
				/**
				 * A​c​h​i​e​v​e​m​e​n​t​s
				 */
				achievement: string
				/**
				 * D​a​i​l​y​ ​Q​u​e​s​t​s
				 */
				dailyQuest: string
				/**
				 * S​p​o​u​s​e
				 */
				spouse: string
				/**
				 * S​h​o​p​k​e​e​p​e​r
				 */
				shop: string
			}
			items: {
				/**
				 * I​t​e​m​s
				 */
				header: string
				/**
				 * S​l​o​t​ ​{​x​}
				 * @param {number} x
				 */
				slot: RequiredParams<'x'>
			}
			application: {
				/**
				 * A​p​p​l​i​c​a​t​i​o​n
				 */
				header: string
				/**
				 * N​e​w​ ​w​i​n​d​o​w
				 */
				newWindow: string
				/**
				 * N​e​w​ ​t​a​b
				 */
				newTab: string
				/**
				 * T​a​b​ ​{​x​}
				 * @param {number} x
				 */
				tab: RequiredParams<'x'>
				/**
				 * S​w​i​t​c​h​ ​t​o​ ​W​i​n​d​o​w​ ​{​x​}
				 * @param {number} x
				 */
				window: RequiredParams<'x'>
				/**
				 * N​e​x​t​ ​t​a​b
				 */
				nextTab: string
				/**
				 * P​r​e​v​i​o​u​s​ ​t​a​b
				 */
				prevTab: string
			}
			spells: {
				/**
				 * S​p​e​l​l​s
				 */
				header: string
				/**
				 * S​l​o​t​ ​{​x​}
				 * @param {number} x
				 */
				slot: RequiredParams<'x'>
			}
			mods: {
				/**
				 * M​o​d​s
				 */
				header: string
				/**
				 * S​h​o​w​/​h​i​d​e​ ​m​a​p​ ​r​e​s​o​u​r​c​e​s
				 */
				mapResources: string
				/**
				 * S​h​o​w​/​h​i​d​e​ ​l​i​f​e​ ​b​a​r​s
				 */
				healthBar: string
			}
			/**
			 * Y​o​u​ ​c​a​n​ ​u​s​e​ ​s​p​e​c​i​a​l​ ​k​e​y​s​ ​C​T​R​L​,​ ​S​H​I​F​T​,​ ​S​P​A​C​E​,​ ​A​L​T​/​C​M​D​ ​Y​o​u​ ​c​a​n​ ​s​p​e​c​i​f​y​ ​y​o​u​r​ ​s​h​o​r​t​c​u​t​ ​b​y​ ​p​r​e​s​s​i​n​g​ ​t​h​e​ ​d​e​s​i​r​e​d​ ​k​e​y​s​ ​a​t​ ​t​h​e​ ​s​a​m​e​ ​t​i​m​e​ ​a​f​t​e​r​ ​s​e​l​e​c​t​i​n​g​ ​t​h​e​ ​i​n​p​u​t
			 */
			information: string
			/**
			 * T​h​i​s​ ​s​h​o​r​t​c​u​t​ ​k​e​y​ ​c​a​n​n​o​t​ ​b​e​ ​u​s​e​d​.
			 */
			error: string
		}
		features: {
			/**
			 * F​e​a​t​u​r​e​s
			 */
			title: string
			general: {
				/**
				 * G​e​n​e​r​a​l
				 */
				header: string
				/**
				 * H​i​d​e​ ​t​h​e​ ​S​h​o​p​ ​b​u​t​t​o​n
				 */
				hideShop: string
				/**
				 * O​p​e​n​ ​m​e​n​u​ ​w​h​e​n​ ​n​o​ ​w​i​n​d​o​w​ ​i​s​ ​o​p​e​n​ ​(​E​S​C​)
				 */
				activeOpenMenu: string
				/**
				 * E​x​t​e​n​d​ ​t​h​e​ ​d​e​l​a​y​ ​b​e​f​o​r​e​ ​d​i​s​c​o​n​n​e​c​t​i​o​n​ ​f​o​r​ ​i​n​a​c​t​i​v​i​t​y
				 */
				disableInactivity: string
				/**
				 * S​h​o​w​ ​z​a​a​p​ ​s​e​a​r​c​h​ ​f​i​l​t​e​r
				 */
				zaapSearchFilter: string
			}
			fight: {
				/**
				 * F​i​g​h​t
				 */
				header: string
				/**
				 * A​c​t​i​v​a​t​e​ ​l​i​f​e​ ​b​a​r​ ​d​i​s​p​l​a​y​ ​b​e​l​o​w​ ​f​i​g​h​t​e​r​s
				 */
				healthBar: string
				/**
				 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​s​w​i​t​c​h​ ​t​o​ ​a​n​ ​a​c​c​o​u​n​t​ ​w​h​e​n​ ​i​t​s​ ​t​u​r​n​ ​s​t​a​r​t​s
				 */
				focusFightTurn: string
				/**
				 * S​h​o​w​ ​s​p​e​l​l​ ​d​a​m​a​g​e​ ​e​s​t​i​m​a​t​i​o​n​s​ ​i​n​ ​b​a​t​t​l​e
				 */
				estimator: string
				/**
				 * S​h​o​w​ ​c​o​m​b​a​t​ ​c​h​r​o​n​o​m​e​t​e​r
				 */
				fightChronometer: string
				/**
				 * D​i​s​p​l​a​y​ ​m​o​n​s​t​e​r​s​ ​g​r​o​u​p​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​m​a​p
				 */
				monsterTooltip: string
				/**
				 * S​h​o​r​t​c​u​t​ ​f​o​r​ ​s​h​o​w​/​h​i​d​e​ ​m​o​n​s​t​e​r​s​ ​t​o​o​l​t​i​p
				 */
				monsterTooltipShortcut: string
				/**
				 * S​h​o​w​ ​f​i​g​h​t​e​r​s​ ​t​i​m​e​l​i​n​e​ ​v​e​r​t​i​c​a​l​l​y
				 */
				verticalTimeline: string
				/**
				 * S​h​o​w​ ​c​h​a​l​l​e​n​g​e​ ​X​P​/​D​r​o​p​ ​b​o​n​u​s
				 */
				challengePercent: string
			}
			group: {
				/**
				 * G​r​o​u​p
				 */
				header: string
				/**
				 * A​d​d​ ​a​n​ ​i​n​d​i​c​a​t​o​r​ ​t​o​ ​k​n​o​w​ ​i​f​ ​g​r​o​u​p​ ​m​e​m​b​e​r​s​ ​a​r​e​ ​o​n​ ​t​h​e​ ​s​a​m​e​ ​m​a​p
				 */
				partyMemberOnMap: string
				partyInfo: {
					/**
					 * S​h​o​w​ ​p​a​r​t​y​'​s​ ​l​e​v​e​l
					 */
					level: string
					/**
					 * S​h​o​w​ ​p​a​r​t​y​'​s​ ​p​r​o​s​p​e​c​t​i​n​g
					 */
					prospecting: string
				}
				autoGroup: {
					/**
					 * A​u​t​o​ ​G​r​o​u​p
					 */
					header: string
					/**
					 * E​n​a​b​l​e​ ​a​u​t​o​m​a​t​i​c​ ​g​r​o​u​p​i​n​g
					 */
					active: string
					/**
					 * B​e​w​a​r​e​,​ ​f​o​l​l​o​w​i​n​g​ ​t​h​e​ ​g​r​o​u​p​ ​l​e​a​d​e​r​ ​c​a​n​ ​b​e​ ​c​o​n​s​i​d​e​r​e​d​ ​a​s​ ​b​o​t​i​n​g​ ​f​o​r​ ​o​t​h​e​r​ ​p​l​a​y​e​r​s​,​ ​u​s​e​ ​i​t​ ​w​i​t​h​ ​c​a​u​t​i​o​n​ ​a​n​d​ ​i​n​ ​u​n​p​o​p​u​l​a​t​e​d​ ​a​r​e​a​s​.
					 */
					warning: string
					/**
					 * B​e​w​a​r​e​,​ ​T​h​i​s​ ​f​e​a​t​u​r​e​ ​c​a​n​ ​b​e​ ​c​o​n​s​i​d​e​r​e​d​ ​a​s​ ​b​o​t​i​n​g​ ​f​o​r​ ​o​t​h​e​r​ ​p​l​a​y​e​r​s​,​ ​u​s​e​ ​i​t​ ​w​i​t​h​ ​c​a​u​t​i​o​n​ ​a​n​d​ ​i​n​ ​u​n​p​o​p​u​l​a​t​e​d​ ​a​r​e​a​s​.
					 */
					warningTimer: string
					/**
					 * T​h​e​ ​c​h​a​r​a​c​t​e​r​s​ ​i​n​ ​t​h​e​ ​g​r​o​u​p​ ​m​u​s​t​ ​b​e​ ​f​r​i​e​n​d​s​ ​w​i​t​h​ ​t​h​e​ ​l​e​a​d​e​r​ ​s​o​ ​t​h​a​t​ ​t​h​e​ ​i​n​v​i​t​a​t​i​o​n​ ​i​s​ ​a​u​t​o​m​a​t​i​c​.
					 */
					explanation1: string
					/**
					 * T​h​e​ ​m​e​m​b​e​r​s​ ​f​o​l​l​o​w​ ​t​h​e​ ​l​e​a​d​e​r​ ​i​f​ ​t​h​e​ ​l​a​t​t​e​r​ ​i​s​ ​o​n​ ​t​h​e​ ​s​a​m​e​ ​m​a​p​.
					 */
					explanation2: string
					/**
					 * N​a​m​e​ ​o​f​ ​l​e​a​d​e​r
					 */
					leader: string
					/**
					 * N​a​m​e​s​ ​o​f​ ​c​h​a​r​a​c​t​e​r​s
					 */
					members: string
					/**
					 * A​d​d​ ​a​ ​c​h​a​r​a​c​t​e​r
					 */
					addMember: string
					/**
					 * F​o​l​l​o​w​ ​t​h​e​ ​g​r​o​u​p​ ​l​e​a​d​e​r
					 */
					followLeader: string
					/**
					 * D​i​s​a​b​l​e​ ​t​h​e​ ​T​i​m​e​r​ ​f​o​r​ ​t​h​e​ ​a​u​t​o​ ​g​r​o​u​p
					 */
					disableTimer: string
					/**
					 * S​k​i​p​ ​"​r​e​a​d​y​"​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
					 */
					ready: string
					/**
					 * E​n​t​e​r​ ​c​o​m​b​a​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
					 */
					fight: string
					/**
					 * T​i​m​e​ ​t​o​ ​f​o​l​l​o​w​ ​(​i​n​ ​s​e​c​o​n​d​s​)
					 */
					delay: string
					/**
					 * F​o​l​l​o​w​ ​t​h​e​ ​l​e​a​d​e​r​ ​o​n​ ​a​ ​m​a​p
					 */
					followOnMap: string
					/**
					 * M​o​v​e​ ​o​n​ ​t​h​e​ ​s​a​m​e​ ​c​e​l​l​ ​t​h​e​ ​l​e​a​d​e​r​ ​m​o​v​e​s
					 */
					strictMove: string
					/**
					 * Y​o​u​ ​c​a​n​'​t​ ​j​o​i​n​ ​a​ ​P​v​P​ ​f​i​g​h​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
					 */
					pvpWarning: string
				}
			}
			job: {
				/**
				 * J​o​b
				 */
				header: string
				/**
				 * S​h​o​w​ ​m​a​p​ ​r​e​s​o​u​r​c​e​s
				 */
				showResources: string
				/**
				 * A​c​t​i​v​a​t​e​ ​d​i​s​p​l​a​y​ ​o​f​ ​r​e​s​s​o​u​r​c​e​s​ ​r​e​m​a​i​n​i​n​g​ ​t​i​m​e
				 */
				harvestIndicator: string
				/**
				 * A​c​t​i​v​a​t​e​ ​t​h​e​ ​d​i​s​p​l​a​y​ ​o​f​ ​j​o​b​ ​x​p​ ​n​e​e​d​e​d​ ​f​o​r​ ​l​e​v​e​l​i​n​g
				 */
				jobsXp: string
			}
			accounts: {
				/**
				 * A​c​c​o​u​n​t​s
				 */
				header: string
			}
		}
		notifications: {
			/**
			 * N​o​t​i​f​i​c​a​t​i​o​n​s
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​r​e​c​e​i​v​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​f​r​o​m​ ​t​h​e​ ​g​a​m​e​ ​w​h​e​n​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​o​n​ ​t​h​e​ ​b​a​c​k​g​r​o​u​n​d​.​ ​Y​o​u​ ​w​i​l​l​ ​b​e​ ​n​o​t​i​f​i​e​d​:
			 */
			description: string
			/**
			 * W​h​e​n​ ​y​o​u​r​ ​t​u​r​n​ ​s​t​a​r​t​s​ ​(​f​i​g​h​t​)
			 */
			fightTurn: string
			/**
			 * W​h​e​n​ ​y​o​u​ ​r​e​c​e​i​v​e​ ​p​r​i​v​a​t​e​ ​m​e​s​s​a​g​e​s
			 */
			privateMessage: string
			/**
			 * W​h​e​n​ ​a​ ​t​a​x​ ​c​o​l​l​e​c​t​o​r​ ​i​s​ ​a​t​t​a​c​k​e​d
			 */
			taxCollector: string
			/**
			 * W​h​e​n​ ​a​ ​k​o​l​i​z​e​u​m​ ​f​i​g​h​t​ ​i​s​ ​f​o​u​n​d
			 */
			kolizeum: string
			/**
			 * W​h​e​n​ ​s​o​m​e​o​n​e​ ​i​n​v​i​t​e​s​ ​y​o​u​ ​t​o​ ​j​o​i​n​ ​a​ ​g​r​o​u​p
			 */
			partyInvitation: string
			/**
			 * W​h​e​n​ ​s​o​m​e​o​n​e​ ​a​g​g​r​e​s​s​e​s​ ​y​o​u
			 */
			aggression: string
			/**
			 * W​h​e​n​ ​a​n​ ​i​t​e​m​ ​i​s​ ​s​o​l​d
			 */
			saleMessage: string
		}
		multiAccount: {
			/**
			 * M​u​l​t​i​ ​A​c​c​o​u​n​t
			 */
			title: string
			/**
			 * E​n​a​b​l​e​ ​t​h​e​ ​m​u​l​t​i​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​y​o​u​r​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d
			 */
			enable: string
			/**
			 * T​o​ ​u​s​e​ ​t​h​i​s​ ​f​e​a​t​u​r​e​,​ ​a​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​c​o​n​f​i​g​u​r​e​d​.​ ​I​t​ ​w​i​l​l​ ​b​e​ ​u​s​e​d​ ​t​o​ ​s​t​a​r​t​ ​N​u​b​l​e​ ​w​i​t​h​ ​m​u​l​t​i​-​a​c​c​o​u​n​t​ ​a​u​t​o​m​a​t​i​o​n​.
			 */
			notConfigured: string
			/**
			 * C​o​n​f​i​g​u​r​e​ ​p​a​s​s​w​o​r​d
			 */
			configurePassword: string
			/**
			 * A​d​d​ ​C​h​a​r​a​c​t​e​r
			 */
			addCharacter: string
			/**
			 * N​e​w​ ​T​e​a​m
			 */
			newTeam: string
			/**
			 * R​e​m​o​v​e​ ​t​h​e​ ​p​a​s​s​w​o​r​d
			 */
			removePassword: string
			/**
			 * C​h​a​n​g​e​ ​t​h​e​ ​p​a​s​s​w​o​r​d
			 */
			changePassword: string
			dialogs: {
				characterDialog: {
					/**
					 * A​d​d​ ​n​e​w​ ​c​h​a​r​a​c​t​e​r​ ​a​c​c​o​u​n​t
					 */
					title: string
					/**
					 * A​d​d
					 */
					confirm: string
					/**
					 * C​a​n​c​e​l
					 */
					cancel: string
				}
				teamDialog: {
					/**
					 * A​d​d​ ​n​e​w​ ​t​e​a​m
					 */
					title: string
					/**
					 * T​e​a​m​ ​N​a​m​e
					 */
					teamName: string
					/**
					 * A​d​d​ ​W​i​n​d​o​w
					 */
					addWindow: string
					/**
					 * S​a​v​e
					 */
					confirm: string
					/**
					 * C​a​n​c​e​l
					 */
					cancel: string
				}
				selectCharacter: {
					/**
					 * S​e​l​e​c​t​ ​a​ ​c​h​a​r​a​c​t​e​r
					 */
					title: string
					/**
					 * C​a​n​c​e​l
					 */
					cancel: string
				}
				passwordDialog: {
					/**
					 * C​o​n​f​i​g​u​r​e​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d
					 */
					configurePassword: string
					/**
					 * C​h​a​n​g​e​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d
					 */
					changePassword: string
					/**
					 * R​e​m​o​v​e​ ​y​o​u​r​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d​ ​?
					 */
					removePassword: string
					/**
					 * I​f​ ​y​o​u​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​m​a​s​t​e​r​ ​p​a​s​s​w​o​r​d​ ​y​o​u​ ​w​i​l​l​ ​l​o​s​t​ ​y​o​u​r​ ​m​u​l​t​i​ ​a​c​c​o​u​n​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n
					 */
					removePasswordInfo: string
					/**
					 * P​a​s​s​w​o​r​d
					 */
					password: string
					/**
					 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
					 */
					confirmPassword: string
					/**
					 * O​l​d​ ​P​a​s​s​w​o​r​d
					 */
					oldPassword: string
					/**
					 * R​e​m​o​v​e​ ​p​a​s​s​w​o​r​d
					 */
					confirmRemovePassword: string
					/**
					 * V​a​l​i​d​a​t​e
					 */
					validate: string
					/**
					 * C​a​n​c​e​l
					 */
					cancel: string
				}
			}
			characterCard: {
				/**
				 * C​h​a​r​a​c​t​e​r​ ​i​m​a​g​e​ ​w​i​l​l​ ​b​e​ ​s​a​v​e​ ​d​u​r​i​n​g​ ​t​h​e​ ​l​o​g​i​n
				 */
				characterImageNotLoaded: string
				buttons: {
					/**
					 * S​e​l​e​c​t
					 */
					select: string
					/**
					 * D​e​l​e​t​e
					 */
					'delete': string
					/**
					 * E​d​i​t
					 */
					edit: string
					/**
					 * R​e​m​o​v​e
					 */
					remove: string
				}
			}
			teamWindowCard: {
				/**
				 * W​i​n​d​o​w​ ​{​p​o​s​i​t​i​o​n​}
				 * @param {number} position
				 */
				window: RequiredParams<'position'>
				/**
				 * A​d​d​ ​C​h​a​r​a​c​t​e​r
				 */
				addCharacter: string
			}
			teamAccordion: {
				/**
				 * D​e​l​e​t​e​ ​t​e​a​m
				 */
				'delete': string
				/**
				 * E​d​i​t​ ​t​e​a​m
				 */
				edit: string
				/**
				 * W​i​n​d​o​w​ ​{​p​o​s​i​t​i​o​n​}
				 * @param {number} position
				 */
				window: RequiredParams<'position'>
			}
		}
		about: {
			/**
			 * A​b​o​u​t
			 */
			title: string
			links: {
				/**
				 * W​e​b​s​i​t​e
				 */
				website: string
				/**
				 * G​i​t​h​u​b​ ​(​s​o​u​r​c​e​ ​c​o​d​e​)
				 */
				github: string
				/**
				 * C​h​a​t​ ​s​e​r​v​e​r
				 */
				chat: string
				/**
				 * R​e​d​d​i​t​ ​(​f​o​r​u​m​)
				 */
				reddit: string
				/**
				 * R​e​l​e​a​s​e​ ​n​o​t​e​s
				 */
				changelog: string
			}
			/**
			 * N​u​b​l​e​ ​i​s​ ​a​ ​s​t​a​t​e​-​o​f​-​t​h​e​-​a​r​t​ ​s​o​f​t​w​a​r​e​ ​t​h​a​t​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​p​l​a​y​ ​D​O​F​U​S​ ​T​o​u​c​h​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r​.
			 */
			text0: string
			/**
			 * U​n​l​i​k​e​ ​a​n​ ​A​n​d​r​o​i​d​ ​e​m​u​l​a​t​o​r​,​ ​t​h​e​ ​c​o​d​e​ ​i​s​ ​d​i​r​e​c​t​l​y​ ​i​n​t​e​r​p​r​e​t​e​d​ ​b​y​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r​,​ ​w​h​i​c​h​ ​m​a​k​e​s​ ​i​t​ ​i​n​c​r​e​d​i​b​l​y​ ​f​a​s​t​ ​s​o​ ​y​o​u​ ​c​a​n​ ​p​l​a​y​ ​D​O​F​U​S​ ​T​o​u​c​h​ ​w​i​t​h​ ​t​h​e​ ​f​u​l​l​ ​p​e​r​f​o​r​m​a​n​c​e​ ​o​f​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r​!
			 */
			text1: string
			/**
			 * D​e​v​e​l​o​p​e​d​ ​b​y​ ​t​h​e​ ​N​u​b​l​e​ ​t​e​a​m​,​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​e​a​t​u​r​e​s​ ​a​n​ ​u​l​t​r​a​-​p​r​e​m​i​u​m​ ​2​0​2​6​ ​b​r​a​n​d​i​n​g​ ​s​t​y​l​e​,​ ​f​l​a​w​l​e​s​s​ ​p​e​r​f​o​r​m​a​n​c​e​,​ ​a​n​d​ ​z​e​r​o​ ​b​u​g​s​.
			 */
			text2: string
		}
	}
	mod: {
		jobXP: {
			/**
			 * {​x​p​}​ ​X​P​ ​m​i​s​s​i​n​g​<​b​r​>​b​e​f​o​r​e​ ​l​e​v​e​l​ ​{​n​e​x​t​L​e​v​e​l​}
			 * @param {number} nextLevel
			 * @param {number} xp
			 */
			xpMissing: RequiredParams<'nextLevel' | 'xp'>
		}
		monsterTooltip: {
			/**
			 * L​e​v​e​l
			 */
			level: string
			/**
			 * G​r​o​u​p
			 */
			group: string
		}
		partyInfo: {
			/**
			 * L​v​l​.
			 */
			level: string
		}
		runeLister: {
			/**
			 * O​b​t​a​i​n​e​d​ ​{​q​u​a​n​t​i​t​y​}​ ​{​r​u​n​e​N​a​m​e​}
			 * @param {number} quantity
			 * @param {string} runeName
			 */
			message: RequiredParams<'quantity' | 'runeName'>
		}
		zaapSearchFilter: {
			/**
			 * S​e​a​r​c​h​ ​a​ ​z​a​a​p
			 */
			placeholder: string
			/**
			 * S​e​a​r​c​h​ ​a​ ​z​a​a​p​i
			 */
			placeholderZaapi: string
			/**
			 * S​e​a​r​c​h​ ​a​ ​p​r​i​s​m​e
			 */
			placeholderPrisme: string
		}
	}
}

export type TranslationFunctions = {
	main: {
		updater: {
			/**
			 * New version available {version}
			 */
			title: (arg: { version: string }) => LocalizedString
			/**
			 * A new version ({version}) of Nuble is available. Do you want to update?
			 */
			message: (arg: { version: string }) => LocalizedString
			/**
			 * A required update ({version}) of Nuble is available, you must download it on GitHub.
			 */
			messageRequired: (arg: { version: string }) => LocalizedString
			/**
			 * Download
			 */
			download: () => LocalizedString
			/**
			 * Ignore
			 */
			ignore: () => LocalizedString
		}
		gameMenu: {
			file: {
				/**
				 * Application
				 */
				title: () => LocalizedString
				/**
				 * New window
				 */
				newWindow: () => LocalizedString
				/**
				 * New tab
				 */
				newTab: () => LocalizedString
				/**
				 * Close tab
				 */
				closeTab: () => LocalizedString
				/**
				 * Exit
				 */
				closeWindow: () => LocalizedString
			}
			edit: {
				/**
				 * Edit
				 */
				title: () => LocalizedString
				/**
				 * Undo
				 */
				undo: () => LocalizedString
				/**
				 * Redo
				 */
				redo: () => LocalizedString
				/**
				 * Cut
				 */
				cut: () => LocalizedString
				/**
				 * Copy
				 */
				copy: () => LocalizedString
				/**
				 * Paste
				 */
				paste: () => LocalizedString
				/**
				 * Select all
				 */
				selectAll: () => LocalizedString
			}
			window: {
				/**
				 * Window
				 */
				title: () => LocalizedString
				/**
				 * Reload
				 */
				reload: () => LocalizedString
				/**
				 * Previous tab
				 */
				prevTab: () => LocalizedString
				/**
				 * Next tab
				 */
				nextTab: () => LocalizedString
				/**
				 * Sound
				 */
				sound: () => LocalizedString
				/**
				 * Turn on sound
				 */
				enableSound: () => LocalizedString
				/**
				 * Turn off sound
				 */
				disableSound: () => LocalizedString
				/**
				 * Zoom in
				 */
				zoomIn: () => LocalizedString
				/**
				 * Zoom out
				 */
				zoomOut: () => LocalizedString
				/**
				 * Reset zoom
				 */
				resetZoom: () => LocalizedString
				/**
				 * Toggle Full screen
				 */
				fullScreen: () => LocalizedString
			}
			infos: {
				/**
				 * ?
				 */
				title: () => LocalizedString
				/**
				 * Release notes
				 */
				changelog: () => LocalizedString
				/**
				 * Developer console
				 */
				console: () => LocalizedString
				/**
				 * About us...
				 */
				about: () => LocalizedString
			}
		}
		dialogs: {
			cacheCleared: {
				/**
				 * Cache cleared
				 */
				title: () => LocalizedString
				/**
				 * Cache has been cleared on currently opened window
				 */
				message: () => LocalizedString
			}
		}
	}
	notifications: {
		/**
		 * Start of turn for {characterName}
		 */
		fightTurn: (arg: { characterName: string }) => LocalizedString
		/**
		 * Incoming message from {senderName}
		 */
		privateMessage: (arg: { senderName: string }) => LocalizedString
		/**
		 * A tax collector is being attacked !
		 */
		taxCollector: () => LocalizedString
		/**
		 * A Kolizeum has been found !
		 */
		kolizeum: () => LocalizedString
		/**
		 * You are invited to join {senderName}'s group.
		 */
		partyInvitation: (arg: { senderName: string }) => LocalizedString
		/**
		 * You have been aggressed !
		 */
		aggression: () => LocalizedString
		/**
		 * Bank
		 */
		saleMessage: () => LocalizedString
	}
	window: {
		main: {
			tabsOverflow: {
				/**
				 * Nuble doesn't support more than 6 tab per window, above that it can be laggy and buggy. But you can open a new window and it will be working just fine.
				 */
				text: () => LocalizedString
			}
		}
		changelog: {
			/**
			 * Release notes
			 */
			title: () => LocalizedString
			/**
			 * Release
			 */
			prefix: () => LocalizedString
		}
		unlockScreen: {
			/**
			 * Enter your master password to connect your dofus touch accounts automatically
			 */
			info: () => LocalizedString
			/**
			 * Choose a team to connect
			 */
			chooseTeamConnect: () => LocalizedString
			/**
			 * Connect
			 */
			connect: () => LocalizedString
			/**
			 * Master password
			 */
			masterPassword: () => LocalizedString
			/**
			 * Invalid password
			 */
			invalidPassword: () => LocalizedString
			/**
			 * Unlock
			 */
			unlock: () => LocalizedString
			/**
			 * Skip
			 */
			skip: () => LocalizedString
		}
		updateGame: {
			/**
			 * Nuble update
			 */
			title: () => LocalizedString
			/**
			 * Preparing update..
			 */
			step0: () => LocalizedString
			/**
			 * Step 1 : Downloading Dofus files
			 */
			step1: () => LocalizedString
			/**
			 * Step 2 : Nuble patch download
			 */
			step2: () => LocalizedString
			/**
			 * Step 3 : Version resolution
			 */
			step3: () => LocalizedString
			/**
			 * Step 4 : Applying the patches
			 */
			step4: () => LocalizedString
			/**
			 * Step 5 : Writing modified files
			 */
			step5: () => LocalizedString
			/**
			 * Step 6 : Delete old files
			 */
			step6: () => LocalizedString
			/**
			 * Step 7 : Finalization
			 */
			step7: () => LocalizedString
			/**
			 * Step 8 : Launch of Nuble..
			 */
			step8: () => LocalizedString
			information: {
				/**
				 * Looking for updates...
				 */
				search: () => LocalizedString
				/**
				 * Can't download the update ! Please try again later
				 */
				error: () => LocalizedString
				/**
				 * Try again
				 */
				retry: () => LocalizedString
			}
		}
		options: {
			/**
			 * Options
			 */
			title: () => LocalizedString
			button: {
				/**
				 * Reset Settings
				 */
				reset: () => LocalizedString
				/**
				 * Close
				 */
				close: () => LocalizedString
			}
			dialogs: {
				resetSettings: {
					/**
					 * Reset all the settings ?
					 */
					title: () => LocalizedString
					/**
					 * All app's settings will be reset to their default value
					 */
					message: () => LocalizedString
					/**
					 * Reset
					 */
					confirm: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
				}
			}
		}
	}
	option: {
		general: {
			/**
			 * General
			 */
			title: () => LocalizedString
			/**
			 * Interface
			 */
			'interface': () => LocalizedString
			/**
			 * Sound
			 */
			sound: () => LocalizedString
			/**
			 * Game data
			 */
			gameData: () => LocalizedString
			/**
			 * Language
			 */
			language: () => LocalizedString
			/**
			 * Resolution
			 */
			resolution: () => LocalizedString
			/**
			 * Full screen
			 */
			fullScreen: () => LocalizedString
			/**
			 * Hide the multi-account tab bar
			 */
			hideTab: () => LocalizedString
			/**
			 * Enable local map download (beta)
			 */
			localContent: () => LocalizedString
			/**
			 * Enable game sound only on foreground window
			 */
			soundFocus: () => LocalizedString
			/**
			 * Play on Dofus Touch Early
			 */
			early: () => LocalizedString
			/**
			 * Apply and restart
			 */
			restart: () => LocalizedString
			/**
			 * Re-download game data
			 */
			resetGame: () => LocalizedString
			/**
			 * Clear cache
			 */
			clearCache: () => LocalizedString
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: () => LocalizedString
			diver: {
				/**
				 * Miscellaneous
				 */
				header: () => LocalizedString
				/**
				 * End your turn / Ready (fight)
				 */
				endTurn: () => LocalizedString
				/**
				 * Open the chat
				 */
				openChat: () => LocalizedString
				/**
				 * Open the menu
				 */
				openMenu: () => LocalizedString
				/**
				 * Go to Upper Map
				 */
				goUp: () => LocalizedString
				/**
				 * Go to Lower Map
				 */
				goDown: () => LocalizedString
				/**
				 * Go to Left Map
				 */
				goLeft: () => LocalizedString
				/**
				 * Go to Right Map
				 */
				goRight: () => LocalizedString
				/**
				 * Show/Hide monster groups tooltips
				 */
				showMonsterTooltips: () => LocalizedString
			}
			interfaces: {
				/**
				 * Interfaces
				 */
				header: () => LocalizedString
				/**
				 * Character
				 */
				carac: () => LocalizedString
				/**
				 * Spells
				 */
				spell: () => LocalizedString
				/**
				 * Inventory
				 */
				bag: () => LocalizedString
				/**
				 * Market place
				 */
				bidHouse: () => LocalizedString
				/**
				 * Map
				 */
				map: () => LocalizedString
				/**
				 * Friends
				 */
				friend: () => LocalizedString
				/**
				 * Quests
				 */
				book: () => LocalizedString
				/**
				 * Guild
				 */
				guild: () => LocalizedString
				/**
				 * Kolizeum
				 */
				conquest: () => LocalizedString
				/**
				 * Shop
				 */
				goultine: () => LocalizedString
				/**
				 * Jobs
				 */
				job: () => LocalizedString
				/**
				 * Alliance
				 */
				alliance: () => LocalizedString
				/**
				 * Mount
				 */
				mount: () => LocalizedString
				/**
				 * List of Guilds and Alliances
				 */
				directory: () => LocalizedString
				/**
				 * Alignment
				 */
				alignment: () => LocalizedString
				/**
				 * Bestiary
				 */
				bestiary: () => LocalizedString
				/**
				 * Titles and Ornaments
				 */
				title: () => LocalizedString
				/**
				 * Achievements
				 */
				achievement: () => LocalizedString
				/**
				 * Daily Quests
				 */
				dailyQuest: () => LocalizedString
				/**
				 * Spouse
				 */
				spouse: () => LocalizedString
				/**
				 * Shopkeeper
				 */
				shop: () => LocalizedString
			}
			items: {
				/**
				 * Items
				 */
				header: () => LocalizedString
				/**
				 * Slot {x}
				 */
				slot: (arg: { x: number }) => LocalizedString
			}
			application: {
				/**
				 * Application
				 */
				header: () => LocalizedString
				/**
				 * New window
				 */
				newWindow: () => LocalizedString
				/**
				 * New tab
				 */
				newTab: () => LocalizedString
				/**
				 * Tab {x}
				 */
				tab: (arg: { x: number }) => LocalizedString
				/**
				 * Switch to Window {x}
				 */
				window: (arg: { x: number }) => LocalizedString
				/**
				 * Next tab
				 */
				nextTab: () => LocalizedString
				/**
				 * Previous tab
				 */
				prevTab: () => LocalizedString
			}
			spells: {
				/**
				 * Spells
				 */
				header: () => LocalizedString
				/**
				 * Slot {x}
				 */
				slot: (arg: { x: number }) => LocalizedString
			}
			mods: {
				/**
				 * Mods
				 */
				header: () => LocalizedString
				/**
				 * Show/hide map resources
				 */
				mapResources: () => LocalizedString
				/**
				 * Show/hide life bars
				 */
				healthBar: () => LocalizedString
			}
			/**
			 * You can use special keys CTRL, SHIFT, SPACE, ALT/CMD You can specify your shortcut by pressing the desired keys at the same time after selecting the input
			 */
			information: () => LocalizedString
			/**
			 * This shortcut key cannot be used.
			 */
			error: () => LocalizedString
		}
		features: {
			/**
			 * Features
			 */
			title: () => LocalizedString
			general: {
				/**
				 * General
				 */
				header: () => LocalizedString
				/**
				 * Hide the Shop button
				 */
				hideShop: () => LocalizedString
				/**
				 * Open menu when no window is open (ESC)
				 */
				activeOpenMenu: () => LocalizedString
				/**
				 * Extend the delay before disconnection for inactivity
				 */
				disableInactivity: () => LocalizedString
				/**
				 * Show zaap search filter
				 */
				zaapSearchFilter: () => LocalizedString
			}
			fight: {
				/**
				 * Fight
				 */
				header: () => LocalizedString
				/**
				 * Activate life bar display below fighters
				 */
				healthBar: () => LocalizedString
				/**
				 * Automatically switch to an account when its turn starts
				 */
				focusFightTurn: () => LocalizedString
				/**
				 * Show spell damage estimations in battle
				 */
				estimator: () => LocalizedString
				/**
				 * Show combat chronometer
				 */
				fightChronometer: () => LocalizedString
				/**
				 * Display monsters groups information on the map
				 */
				monsterTooltip: () => LocalizedString
				/**
				 * Shortcut for show/hide monsters tooltip
				 */
				monsterTooltipShortcut: () => LocalizedString
				/**
				 * Show fighters timeline vertically
				 */
				verticalTimeline: () => LocalizedString
				/**
				 * Show challenge XP/Drop bonus
				 */
				challengePercent: () => LocalizedString
			}
			group: {
				/**
				 * Group
				 */
				header: () => LocalizedString
				/**
				 * Add an indicator to know if group members are on the same map
				 */
				partyMemberOnMap: () => LocalizedString
				partyInfo: {
					/**
					 * Show party's level
					 */
					level: () => LocalizedString
					/**
					 * Show party's prospecting
					 */
					prospecting: () => LocalizedString
				}
				autoGroup: {
					/**
					 * Auto Group
					 */
					header: () => LocalizedString
					/**
					 * Enable automatic grouping
					 */
					active: () => LocalizedString
					/**
					 * Beware, following the group leader can be considered as boting for other players, use it with caution and in unpopulated areas.
					 */
					warning: () => LocalizedString
					/**
					 * Beware, This feature can be considered as boting for other players, use it with caution and in unpopulated areas.
					 */
					warningTimer: () => LocalizedString
					/**
					 * The characters in the group must be friends with the leader so that the invitation is automatic.
					 */
					explanation1: () => LocalizedString
					/**
					 * The members follow the leader if the latter is on the same map.
					 */
					explanation2: () => LocalizedString
					/**
					 * Name of leader
					 */
					leader: () => LocalizedString
					/**
					 * Names of characters
					 */
					members: () => LocalizedString
					/**
					 * Add a character
					 */
					addMember: () => LocalizedString
					/**
					 * Follow the group leader
					 */
					followLeader: () => LocalizedString
					/**
					 * Disable the Timer for the auto group
					 */
					disableTimer: () => LocalizedString
					/**
					 * Skip "ready" automatically
					 */
					ready: () => LocalizedString
					/**
					 * Enter combat automatically
					 */
					fight: () => LocalizedString
					/**
					 * Time to follow (in seconds)
					 */
					delay: () => LocalizedString
					/**
					 * Follow the leader on a map
					 */
					followOnMap: () => LocalizedString
					/**
					 * Move on the same cell the leader moves
					 */
					strictMove: () => LocalizedString
					/**
					 * You can't join a PvP fight automatically
					 */
					pvpWarning: () => LocalizedString
				}
			}
			job: {
				/**
				 * Job
				 */
				header: () => LocalizedString
				/**
				 * Show map resources
				 */
				showResources: () => LocalizedString
				/**
				 * Activate display of ressources remaining time
				 */
				harvestIndicator: () => LocalizedString
				/**
				 * Activate the display of job xp needed for leveling
				 */
				jobsXp: () => LocalizedString
			}
			accounts: {
				/**
				 * Accounts
				 */
				header: () => LocalizedString
			}
		}
		notifications: {
			/**
			 * Notifications
			 */
			title: () => LocalizedString
			/**
			 * You can receive notifications from the game when the application is on the background. You will be notified:
			 */
			description: () => LocalizedString
			/**
			 * When your turn starts (fight)
			 */
			fightTurn: () => LocalizedString
			/**
			 * When you receive private messages
			 */
			privateMessage: () => LocalizedString
			/**
			 * When a tax collector is attacked
			 */
			taxCollector: () => LocalizedString
			/**
			 * When a kolizeum fight is found
			 */
			kolizeum: () => LocalizedString
			/**
			 * When someone invites you to join a group
			 */
			partyInvitation: () => LocalizedString
			/**
			 * When someone aggresses you
			 */
			aggression: () => LocalizedString
			/**
			 * When an item is sold
			 */
			saleMessage: () => LocalizedString
		}
		multiAccount: {
			/**
			 * Multi Account
			 */
			title: () => LocalizedString
			/**
			 * Enable the multi account with your master password
			 */
			enable: () => LocalizedString
			/**
			 * To use this feature, a password must be configured. It will be used to start Nuble with multi-account automation.
			 */
			notConfigured: () => LocalizedString
			/**
			 * Configure password
			 */
			configurePassword: () => LocalizedString
			/**
			 * Add Character
			 */
			addCharacter: () => LocalizedString
			/**
			 * New Team
			 */
			newTeam: () => LocalizedString
			/**
			 * Remove the password
			 */
			removePassword: () => LocalizedString
			/**
			 * Change the password
			 */
			changePassword: () => LocalizedString
			dialogs: {
				characterDialog: {
					/**
					 * Add new character account
					 */
					title: () => LocalizedString
					/**
					 * Add
					 */
					confirm: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
				}
				teamDialog: {
					/**
					 * Add new team
					 */
					title: () => LocalizedString
					/**
					 * Team Name
					 */
					teamName: () => LocalizedString
					/**
					 * Add Window
					 */
					addWindow: () => LocalizedString
					/**
					 * Save
					 */
					confirm: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
				}
				selectCharacter: {
					/**
					 * Select a character
					 */
					title: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
				}
				passwordDialog: {
					/**
					 * Configure master password
					 */
					configurePassword: () => LocalizedString
					/**
					 * Change master password
					 */
					changePassword: () => LocalizedString
					/**
					 * Remove your master password ?
					 */
					removePassword: () => LocalizedString
					/**
					 * If you remove your master password you will lost your multi account configuration
					 */
					removePasswordInfo: () => LocalizedString
					/**
					 * Password
					 */
					password: () => LocalizedString
					/**
					 * Confirm Password
					 */
					confirmPassword: () => LocalizedString
					/**
					 * Old Password
					 */
					oldPassword: () => LocalizedString
					/**
					 * Remove password
					 */
					confirmRemovePassword: () => LocalizedString
					/**
					 * Validate
					 */
					validate: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
				}
			}
			characterCard: {
				/**
				 * Character image will be save during the login
				 */
				characterImageNotLoaded: () => LocalizedString
				buttons: {
					/**
					 * Select
					 */
					select: () => LocalizedString
					/**
					 * Delete
					 */
					'delete': () => LocalizedString
					/**
					 * Edit
					 */
					edit: () => LocalizedString
					/**
					 * Remove
					 */
					remove: () => LocalizedString
				}
			}
			teamWindowCard: {
				/**
				 * Window {position}
				 */
				window: (arg: { position: number }) => LocalizedString
				/**
				 * Add Character
				 */
				addCharacter: () => LocalizedString
			}
			teamAccordion: {
				/**
				 * Delete team
				 */
				'delete': () => LocalizedString
				/**
				 * Edit team
				 */
				edit: () => LocalizedString
				/**
				 * Window {position}
				 */
				window: (arg: { position: number }) => LocalizedString
			}
		}
		about: {
			/**
			 * About
			 */
			title: () => LocalizedString
			links: {
				/**
				 * Website
				 */
				website: () => LocalizedString
				/**
				 * Github (source code)
				 */
				github: () => LocalizedString
				/**
				 * Chat server
				 */
				chat: () => LocalizedString
				/**
				 * Reddit (forum)
				 */
				reddit: () => LocalizedString
				/**
				 * Release notes
				 */
				changelog: () => LocalizedString
			}
			/**
			 * Nuble is a state-of-the-art software that allows you to play DOFUS Touch directly from your computer.
			 */
			text0: () => LocalizedString
			/**
			 * Unlike an Android emulator, the code is directly interpreted by your computer, which makes it incredibly fast so you can play DOFUS Touch with the full performance of your computer!
			 */
			text1: () => LocalizedString
			/**
			 * Developed by the Nuble team, this application features an ultra-premium 2026 branding style, flawless performance, and zero bugs.
			 */
			text2: () => LocalizedString
		}
	}
	mod: {
		jobXP: {
			/**
			 * {xp} XP missing<br>before level {nextLevel}
			 */
			xpMissing: (arg: { nextLevel: number, xp: number }) => LocalizedString
		}
		monsterTooltip: {
			/**
			 * Level
			 */
			level: () => LocalizedString
			/**
			 * Group
			 */
			group: () => LocalizedString
		}
		partyInfo: {
			/**
			 * Lvl.
			 */
			level: () => LocalizedString
		}
		runeLister: {
			/**
			 * Obtained {quantity} {runeName}
			 */
			message: (arg: { quantity: number, runeName: string }) => LocalizedString
		}
		zaapSearchFilter: {
			/**
			 * Search a zaap
			 */
			placeholder: () => LocalizedString
			/**
			 * Search a zaapi
			 */
			placeholderZaapi: () => LocalizedString
			/**
			 * Search a prisme
			 */
			placeholderPrisme: () => LocalizedString
		}
	}
}

export type Formatters = {}
